apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xboe70f7m-nodejs 
  janus-idp.io/tekton: xboe70f7m-nodejs
  backstage.io/kubernetes-id: xboe70f7m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xboe70f7m-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  